version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
      
# With depends_on above we make sure that redis has been started before running Redis Commander
volumes:
  postgres:
    name: spirity-db
  pgadmin:

networks:
  postgres:
    driver: bridge